---
  - { role: geerlingguy.ntp }
  - { role: mikegleasonjr.firewall }
  - { role: 'git+https://github.com/nexcess/ansible-role-server.git' }
  - { role: 'git+https://github.com/clwells/ansible-role-clwells.git' }
